### ISSUE TITLE
 Review documentation related with new MQTT topic prefix

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/thinking-cities#125]
In addition to the IOTA-UL and IOTA-JSON documentation review (issues https://github.com/telefonicaid/iotagent-ul/issues/402 and https://github.com/telefonicaid/iotagent-json/issues/451) the Thinking Cities documentation should be also reviewed and changed properly.

**Comment by AlvaroVega** [comment]
fixed in https://github.com/telefonicaid/thinking-cities/pull/126
